- jose/jwt.go
Use the claims type rather than passing a map to `NewSignedJWT(...)`
> jose: Use claims type instead of map for NewSignedJWT

- oauth2/oauth2.go
Some oauth2 implementations don't have an 'expires' or 'expires_in'
field, specifically GitHub. Don't fail if this happens.
Needed to use this package for coreos/dex#191
> oauth2: don't fail if the token response does not expire

- oidc/client.go
- oidc/client_race_test.go
- oidc/client_test.go
- oidc/provider.go
- test
Add a RWMutex around a client's provider config to prevent race conditions when updating after syncing.
Test added which triggered the race condition before this change.
cc @yifan-gu, @bobbyrullo
> oidc: guard client provider config against race conditions

- oidc/provider.go
- oidc/provider_test.go
"id_token_signing_alg_values_supported" is a required field in the OIDC provider metadata response and currently misnamed as "id_token_alg_values_supported". This commit corrects the field name.
Fixes #32
> oidc: fix provider config field misname

- key/key.go
Per @gtank's recommendations, increase the default RSA key size in
GeneratePrivateKey from 1024 to 2048 bits.
Closes #15
> key: increase default RSA key size from 1024 to 2048 bits

- key/repo.go
- key/sync.go
- key/sync_test.go
Fix race condition in TestKeySyncerSync which was triggering the race detector for Go 1.5.X. Rename "sync" function so we can import the "sync" package and add RWMutexes to settable types.
Fixes #28
> key: fix race condition in TestKeySyncerSync

- .travis.yml
- jose/jose.go
- jose/jwk.go
- oauth2/oauth2.go
- oauth2/oauth2_test.go
- oidc/client.go
- oidc/client_race_test.go
- oidc/client_test.go
- oidc/provider.go
- oidc/provider_test.go
Update this package to hold structs required for dynamic client registration. ClientMetadata and ClientRegistrationResponse.
This commit is breaking. It updates ClientMetadata to be JSON compatible with the spec by
1. renaming `RedirectURLs` to `RedirectURIs` as per [the spec](http://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata)
2. changing that field's type from `[]url.URL` to `[]string` for JSON serialization 
The tests affected by this change have been rectified. We will have to make a few changes to dex when updating this package (which we'll have to anyway to store the added fields in the client metadata).
@bobbyrullo I don't know if this will fly, but I'd like to get your feedback nonetheless. Would it be better to keep `RedirectURLs` and list it deprecated?
> oidc: update client metadata and provider config to support dynamic registration spec

- oidc/client.go
- oidc/client_test.go
- oidc/provider.go
- oidc/provider_test.go
From out of bounds conversation with @bobbyrullo.
1. Make ClientMetadata slice fields non-nillable e7e315eb55ea0318af5de7f3f2c83f1026fe7ca2
2. Remove JWAValuesSupported struct 193a278be42b4ecc4f05be0c06226e4c9fd884f1
> oidc: clean up provider and client metadata fields

- oidc/client.go
Error found when working on dex. If parsing a URI fails, the parser
will attempt to get the concrete value of a nil pointer.
> oidc: fix decoding panic case

- http/client.go
- oauth2/oauth2_test.go
- oidc/provider_test.go
- oidc/transport_test.go
Users should just use net/http/httptest instead.
Closes #57
> http: remove HandlerClient and RequestRecorder

- jose/sig.go
- jose/sig_hmac.go
- jose/sig_rsa.go
- oidc/key.go
**JOSE**
JWK's "kty" parameter is case-sensitive:
https://tools.ietf.org/html/rfc7517#section-4.1
The "alg" parameter is case-sensitive and optional:
https://tools.ietf.org/html/rfc7517#section-4.4
Given that it is optional, I think it's safe to assume that there should be a default (the specification has a "recommended" algorithm for each "kty"). This appears to be the behaviour with other clients and servers.
**OIDC**
The specification only states that jwks_uri SHOULD have a Cache-Control header:
http://openid.net/specs/openid-connect-core-1_0.html#rfc.section.10.2.1
> jose/oidc fixes for non-comformity

- key/key.go
- key/key_test.go
Because the `MarshalJSON()` method implemented by `jose/JWK` has a pointer receiver, we must pass a pointer to it. Otherwise, the method is never called when a `key/PublicKey` instance is marshaled, the Go default MarshalJSON function is used on `jose/JWK`. Consequently, the JSON data for a PublicKey is invalid (i.e. modulus and exponent are not properly encoded) and it is impossible to unmarshal it back to a valid PublicKey.
> Fixed PublicKey JSON Marshaling

- .travis.yml
- test
Not sure what happened in #70's travis run, but `1.6` is missing there. Not sure about also dropping `1.4`?
> update go in travis

- oauth2/oauth2.go
This is a prerequisite to a fix for https://github.com/coreos/dex/issues/395.
Happy to add tests if you agree this is potentially mergeable.
(Things will look different with #64, but I'd be happy to help transitioning, too.)
> oauth2: return embedded http client

- oidc/transport.go
- oidc/transport_test.go
This support the case in which you have a Token already that may or may
not be invalidated.
> oidc: Export JWT in AuthenticatedTransport

- oidc/provider.go
- changing from info to debug level on the provider config as it more debug and required information. On similar note, it would be nice to allow the consumer to set the io.Writer on the logs?
> removing the debug log

- oauth2/oauth2.go
- oauth2/oauth2_test.go
This change adds support for Azure AD token response on Code Flow.
Though RFC6749 section 5.1 states Numerical values are included as
JSON numbers, Azure AD returns "expires_in" value as string.
see Azure AD JSON example
https://msdn.microsoft.com/en-us//library/azure/dn645542.aspx
> oauth2: add support for Azure AD

- key/key.go
- key/key_test.go
Use shorter KeyIDs to reduce the overall size of JWTs produced by
this package.
The "kid" field value is unspecified and only exists to uniquely
identity keys in a JSONKeySet.[0] Therefore changing how we
generate this value shouldn't impact any existing programs.
This addresses coreos/dex#474
[0] https://tools.ietf.org/html/rfc7517#section-4.5
cc @chancez @sym3tri
> key: use shorter key ids

- oidc/verification.go
- oidc/verification_test.go
Checking claims is a much lighter weight operation than verifying
signatures and re-syncing keys. While we still ensure that all JWTs
are correctly signed and valid, throw out tokens we know are invalid
based on claims before attempting to validate the signature.
Closes #93
> oidc: verify claims before signatures

- jose/sig_hmac.go
This mirrors similar logic in square/go-jose[0] and dgrijalva/jwt-go[1].
[0] https://github.com/square/go-jose/blob/5848f914/symmetric.go#L317-L324
[1] https://github.com/dgrijalva/jwt-go/blob/63734eae/hmac.go#L71
Closes #98
> jose: use constant time comparison for HMAC verification

- jose/jwt_test.go
Changed function name from 'TestNewJWTHeaderTyp' to 'TestNewJWTHeaderType' for better readability.
> Updating a function name for better readability

- jose/jwk.go
Per JWS rfc7515 (Section 2. Terminology, Base64url Encoding), all
trailing '=' characters should be omitted. coreos/go-oidc/jose doesn't
implement this requirement.
While this was Ok when coreos/go-oidc/jose was used on both client and
server side, or when it was used on client side only (due to
decodeBase64URLPaddingOptional function), it stopped working when
go-oidc/jose is used on server side and stricter implementation of JWS
is used on the client side (notable, square/go-jose.v2 which is used by
new coreos/go-oidc package).
By following the RFC more strictly on the encoding side we:
- allow to use new go-oidc package on the client side with
DEX server v1, which relies on old go-oidc package;
- don't break compatibility with existing software, as decoding
handles both padded and …
> jose: use base64 raw URL encoding for modulus and exponent

- .travis.yml
- key/key_test.go
- test
Commit e7893b34 changed the way keys' exponent and modulus are encoded,
but didn't fix the test to expect new format.
Fix the test here.
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>
> key: fix test fail introduced by e7893b34

- oidc.go
It seem that the current `UserInfo` function does not use the `tokenSource` to authenticate properly with the `/userinfo` endpoint (indeed `tokenSource` is not used at all in the `UserInfo` function. This PR replaces the `clientFromContext` call with an [`oauth2.NewClient`](https://godoc.org/golang.org/x/oauth2#NewClient) call that returns a token-aware HTTP client.
There are several other approaches that resolve non-authentication issue, such as:
* setting the client in the context and retaining the call to `clientFromContext`
* using the `oauth2.SetAuthHeader()` for the request that is passed to the HTTP client returned from `clientFromContext`
The latter option will always respect the HTTP client set by the context, but [the `SetAuthHeader` docs …
> Use a token-aware HTTP client for UserInfo

- example/README.md
Fixed typo in the go run command.
> example: Correct go run command in README.

- example/idtoken/app.go
- example/nonce/app.go
- verify.go
- verify_test.go
Closes #128.
The current ID Token validation is driven by the VerificationOptions argument provided to the Verifier. Thus we do not implement some of "Must Checks" in the OIDC spec (https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation).
This change ensures that the ID Token validation process has stronger defaults, in turn making it more secure. We still provide the option to skip these default checks via the configuration attributes in the Config struct.
As a part of this change I also updated the example apps and the tests in verify_test.go.
> *: Update ID token Validation according to OIDC spec.

- oidc.go
- verify.go
- verify_test.go
Google sometimes returns "accounts.google.com" instead of
"https://accounts.google.com". Special case this.
Originally we merged a new verification flag, but since this should
only be used with Google, and should always be on with Google, it
makes more sense for us to detect this case transparently.
Fixes #125
cc @ksswr @rithujohn191
> special case google accounts issuer validation

- oidc/provider.go
- oidc/provider_test.go
Maintenance patch for the deprecated `oidc` package
Fixes #137
cc:/ @ericchiang
> oidc: allow `none` in TokenEndpointAuthMethodsSupported

- jwks.go
- oidc.go
If the Content-Type is not "application/json", add extra text indicating
that the response was not JSON before propagating the unmarshal error to
the caller.
> Check response content-type to improve message if cannot decode as JSON

- http/http.go
- http/http_test.go
- oidc/provider_test.go
This is allowed by the RFC and is common with a few OIDC providers.
Partially addresses #136 as a temporary solution until k8s uses the top level package
/cc @ericchiang
> fix(http): Allows 0 as an `Expires` header value
